### ISSUE TITLE
adjust span for PERSONS with "'s" in answer or choice

### ISSUE THREAD

**Issue by danielsgriffin** [TheGadflyProject/TheGadflyProject#34]
Fix developed with `remove_apos_s_choices` and `remove_apos_s_ans` in `HeuristicEvaluator`

Issue found in MCQ EDA Trial 1 (see row#69)
filename: `‘This Leak Is Big ... Heads Should Roll’ - The New York Times.txt`

**Pre-fix:**
issue in answer:
`Q: — Kierstan Boyd on The Times's Facebook page, reacting to ___________ retirement from the N.F.L. at age 23 because of concussions., Choices: {'Gram Parsons', 'Rollie Massimino', "A.J. Tarpley's", 'John Blue'}, A: A.J. Tarpley's`

issue in choices:
`Q: Or consider in the crowd, the old basketball coach, ___________ , who coached Villanova to a shocking upset of the mighty Hoyas of Georgetown, led by Patrick Ewing in 1985., Choices: {'Gram Parsons', 'Rollie Massimino', "A.J. Tarpley's", 'John Blue'}, A: Rollie Massimino`

**Post-fix:**
issue in answer:
`Q: — Kierstan Boyd on The Times's Facebook page, reacting to ___________ 's retirement from the N.F.L. at age 23 because of concussions., Choices: {'Stephen Brannon', 'Snapchat', 'A.J. Tarpley', 'Elia Malgieri'}, A: A.J. Tarpley`

issue in choices:
`Q: — ___________ , New York, 72, responding to a callout for reaction to Pope Francis ' statement on the family , which seemed to open the door for divorced and remarried couples to receive communion., Choices: {'Elia Malgieri', 'A.J. Tarpley', 'Nate Britt', 'Civis Romanus Sum'}, A: Elia Malgieri`

**Comment by danielsgriffin** [comment]
There may be a better solution somewhere in this, rather than our hacky method of converting to ent_text: "I extended Spans to have the same ents property that is defined in Doc" https://github.com/spacy-io/spaCy/issues/156

**Comment by danielsgriffin** [comment]
Also note, this is only implemented for MCQ for now.

**Comment by Anand-** [comment]
Extending span sounds like a great idea.
