### ISSUE TITLE
dealing with "(Reporting by ...)" in NYT

### ISSUE THREAD

**Issue by danielsgriffin** [TheGadflyProject/TheGadflyProject#39]
There were 70 instances of this pattern in MCQ EDA Trial 1 and 6 of "(Writing by ...)"
Ex. (filename: `Obama to Meet Fed Chair Yellen on Monday.txt`)
```
v.mcq_g: DEBUG: Question:
v.mcq_g: DEBUG: (Reporting by ___________ ; Editing by Peter Cooney)
v.mcq_g: DEBUG: PERSON
v.mcq_g: DEBUG: ent_text: David Chance
v.mcq_g: DEBUG: answer_choices: ['Barack Obama', 'Joe Biden', 'Janet Yellen', 'David Chance']
```
Two issues: 

- this becoming a question
- these entities being answer choices (less important; perhaps not important at all)

**Comment by danielsgriffin** [comment]
Instituted fix in `q_generator_base.py`:
(In the function `tfidf` before sending sents through `TF_IDFSummarizer`)

```
    # Issue  #39
    if sents[-1][0].orth_ == "(" and sents[-1][1].orth_ in ["Reporting",
                                                            "Writing"]:
            sents = sents[:-1]
```

**Comment by vijayv** [comment]
Added regex to API to fix:

`((Reporting by)||(Editing by))(\s\w+)+`
